// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurante_GR07.Models;

#nullable disable

namespace Restaurante_GR07.Migrations
{
    [DbContext(typeof(RestauranteContext))]
    [Migration("20260615185333_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurante_GR07.Models.Comprador", b =>
                {
                    b.Property<string>("id_comprador")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id_comprador");

                    b.ToTable("Compradores");
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Producto", b =>
                {
                    b.Property<string>("id_producto")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Compradorid_comprador")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("color_producto")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("descripcion_producto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("dimensiones_producto")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("estado_producto")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("fecha_publicacion_producto")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("foto_producto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("nombre_producto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("talla_producto")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("usuario_tienda")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_producto");

                    b.HasIndex("Compradorid_comprador");

                    b.HasIndex("usuario_tienda");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Reseña", b =>
                {
                    b.Property<string>("id_reseña")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("calificacion_reseña")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("descripcion_reseña")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("id_comprador")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("usuario_tienda")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("valor_reseña")
                        .HasColumnType("real");

                    b.HasKey("id_reseña");

                    b.HasIndex("id_comprador");

                    b.HasIndex("usuario_tienda");

                    b.ToTable("Reseñas");
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Tienda", b =>
                {
                    b.Property<string>("usuario_tienda")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("descripcion_tienda")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("fecha_creacion_tienda")
                        .HasColumnType("datetime2");

                    b.Property<string>("id_vendedor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<byte[]>("logo_local")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("nombre_local")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ruc_local")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<float>("ubicacion_tienda")
                        .HasColumnType("real");

                    b.HasKey("usuario_tienda");

                    b.HasIndex("id_vendedor")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Usuario", b =>
                {
                    b.Property<string>("id_usuario")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("apellidos_usuario")
                        .IsRequired()
                        .HasMaxLength(51)
                        .HasColumnType("nvarchar(51)");

                    b.Property<string>("contrasena_usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("correo_usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nombres_usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("ubicacion_usuario")
                        .HasColumnType("real");

                    b.HasKey("id_usuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            id_usuario = "david_p",
                            apellidos_usuario = "Pilatasig",
                            contrasena_usuario = "$2a$11$fcd6W4lBL10IgehkzNmivebuENPGs0KgpFqu84OmxqjkUG4rFwVO.",
                            correo_usuario = "david.pilatasig@restaurante.com",
                            nombres_usuario = "David",
                            ubicacion_usuario = 0f
                        },
                        new
                        {
                            id_usuario = "simo",
                            apellidos_usuario = "Medina",
                            contrasena_usuario = "$2a$11$oxwk0QJ.kzCEVC0riW23zehnrfb9wp/4fJGAfyV8Z8mIOXz5RiHhS",
                            correo_usuario = "administrador@restaurante.com",
                            nombres_usuario = "Simoné",
                            ubicacion_usuario = 0f
                        });
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Vendedor", b =>
                {
                    b.Property<string>("id_vendedor")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id_vendedor");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Comprador", b =>
                {
                    b.HasOne("Restaurante_GR07.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Restaurante_GR07.Models.Comprador", "id_comprador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Producto", b =>
                {
                    b.HasOne("Restaurante_GR07.Models.Comprador", null)
                        .WithMany("ProductosSolicitados")
                        .HasForeignKey("Compradorid_comprador");

                    b.HasOne("Restaurante_GR07.Models.Tienda", "Tienda")
                        .WithMany("Productos")
                        .HasForeignKey("usuario_tienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Reseña", b =>
                {
                    b.HasOne("Restaurante_GR07.Models.Comprador", "Comprador")
                        .WithMany()
                        .HasForeignKey("id_comprador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurante_GR07.Models.Tienda", "Empresa")
                        .WithMany()
                        .HasForeignKey("usuario_tienda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Tienda", b =>
                {
                    b.HasOne("Restaurante_GR07.Models.Vendedor", "Vendedor")
                        .WithOne("Tienda")
                        .HasForeignKey("Restaurante_GR07.Models.Tienda", "id_vendedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Vendedor", b =>
                {
                    b.HasOne("Restaurante_GR07.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Restaurante_GR07.Models.Vendedor", "id_vendedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Comprador", b =>
                {
                    b.Navigation("ProductosSolicitados");
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Tienda", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Restaurante_GR07.Models.Vendedor", b =>
                {
                    b.Navigation("Tienda");
                });
#pragma warning restore 612, 618
        }
    }
}
